from __future__ import annotations

import re
from typing import Any, Dict, List
from .models import PreSpecSession
from .decision_graph import get_agent_summary


def slugify_name(text: str, fallback: str) -> str:
    text = text.lower()
    if "svn" in text and "review" in text:
        return "svn-reviewer"
    if "公众号" in text or "wechat" in text:
        return "wechat-ai-writer"
    text = re.sub(r"[^a-z0-9\u4e00-\u9fff]+", "-", text).strip("-")
    if not text or re.search(r"[\u4e00-\u9fff]", text):
        return fallback
    return text[:48].strip("-") or fallback


def compile_agentspec(session: PreSpecSession, agent_name: str | None = None) -> Dict[str, Any]:
    if session.inferred_agent_type == "review-agent":
        return _compile_review_agent(session, agent_name)
    if session.inferred_agent_type == "writing-agent":
        return _compile_writing_agent(session, agent_name)
    return _compile_generic_agent(session, agent_name)


def _base(session: PreSpecSession, agent_name: str | None, fallback_name: str) -> Dict[str, Any]:
    summary = get_agent_summary(session.inferred_agent_type, session.user_goal)
    name = agent_name or slugify_name(session.user_goal, fallback_name)
    return {
        "agent": {
            "name": name,
            "version": "0.1.0",
            "type": session.inferred_agent_type,
            "description": f"{summary.title} generated by Agent Foundry MVP.",
        },
        "source": {
            "user_goal": session.user_goal,
            "pre_spec_session_id": session.id,
            "selected_preset": session.selected_preset,
            "llm_provider": session.metadata.get("llm_provider"),
            "llm_design": session.metadata.get("llm_design"),
        },
        "custom_decisions": _custom_decisions(session),
    }


def _decision(session: PreSpecSession, key: str, default: Any) -> Any:
    return session.get_value(key, default)


def _custom_decisions(session: PreSpecSession) -> Dict[str, Any]:
    dynamic_ids = {q.get("id") for q in session.metadata.get("llm_dynamic_questions", []) if q.get("id")}
    return {
        key: value.to_dict()
        for key, value in session.decisions.items()
        if key in dynamic_ids or key.startswith("custom_")
    }


def _compile_review_agent(session: PreSpecSession, agent_name: str | None) -> Dict[str, Any]:
    spec = _base(session, agent_name, "svn-reviewer")
    context = _decision(session, "context_scope", "project_search")
    run_tests = _decision(session, "run_tests", "ask")
    patch = _decision(session, "patch_policy", "suggestion_only")
    source_modify = _decision(session, "source_modify_policy", "ask")
    feedback = _decision(session, "finding_feedback", "inline_labels")
    memory_policy = _decision(session, "memory_policy", "approved_rule_patch")
    output_format = _decision(session, "output_format", "markdown_report")
    autonomy_level = _decision(session, "autonomy_level", "L2")
    max_iter = int(_decision(session, "max_iterations_without_user", "3"))
    review_focus = _decision(session, "review_focus", ["bug_risk", "maintainability", "test_impact"])
    lifecycle = _decision(session, "lifecycle", "on_demand")

    read_scope = {
        "diff_only": "changed_files_only",
        "same_directory": "same_directory",
        "project_search": "current_project",
        "custom": session.get_inputs("context_scope").get("context_custom_scope", "custom_scope"),
    }.get(context, "current_project")

    code_search_permission = "deny" if context == "diff_only" else "allow"
    test_permission = {"deny": "deny", "ask": "ask", "allow_whitelist": "allow"}.get(run_tests, "ask")
    whitelist_raw = session.get_inputs("run_tests").get("test_command_whitelist", [])
    if isinstance(whitelist_raw, str):
        whitelist = [x.strip() for x in re.split(r"[,\n]", whitelist_raw) if x.strip()]
    else:
        whitelist = whitelist_raw

    patch_permission = "deny"
    modify_permission = "deny"
    if patch == "write_patch_ask":
        patch_permission = "ask"
    elif patch == "modify_workspace_ask":
        patch_permission = "ask"
        modify_permission = "ask"
    if source_modify == "ask":
        modify_permission = "ask"
    elif source_modify == "allow_sandbox_only":
        modify_permission = "ask"
    elif source_modify == "deny":
        modify_permission = "deny"

    if output_format == "html_and_markdown":
        artifacts = ["review_report.md", "review_report.html", "findings.json", "test_suggestions.md", "rule_patch_proposal.md"]
    else:
        artifacts = ["review_report.md", "findings.json", "test_suggestions.md", "rule_patch_proposal.md"]
        if patch in ["write_patch_ask", "modify_workspace_ask"]:
            artifacts.append("optional_patch.diff")

    spec.update(
        {
            "goal": {
                "primary": "审查 SVN / diff 变更，发现潜在问题并生成可执行的 Review 报告。",
                "secondary": ["降低人工 Review 成本", "沉淀项目审查规则", "减少重复误报"],
                "focus": review_focus,
            },
            "lifecycle": {
                "mode": lifecycle,
                "trigger": ["manual", "diff_available"] if lifecycle != "scheduled" else ["schedule"],
            },
            "autonomy": {
                "level": autonomy_level,
                "max_iterations_without_user": max_iter,
                "default_behavior": "auto_low_risk_ask_high_risk",
            },
            "inputs": {
                "required": ["svn_diff"],
                "optional": ["related_source_files", "project_rules", "previous_feedback"],
            },
            "tools": {
                "required_capabilities": [
                    "read_svn_diff",
                    "read_files",
                    "search_code",
                    "generate_markdown",
                    "ask_user",
                    "propose_rule_patch",
                ]
            },
            "tool_policy": {
                "svn.diff": {"permission": "allow", "risk": "low"},
                "fs.read": {"permission": "allow", "scope": read_scope, "risk": "low_to_medium"},
                "code.search": {"permission": code_search_permission, "scope": read_scope, "risk": "low_to_medium"},
                "shell.run_tests": {"permission": test_permission, "allowed_commands": whitelist, "risk": "medium"},
                "fs.write_patch": {"permission": patch_permission, "risk": "medium_high"},
                "fs.modify_source": {"permission": modify_permission, "risk": "high"},
                "svn.commit": {"permission": "deny", "risk": "critical"},
            },
            "human_feedback": {
                "finding_feedback": {
                    "mode": feedback,
                    "options": ["accepted", "false_positive", "too_minor", "duplicate", "needs_more_evidence"],
                },
                "before_run_tests": {"mode": "approval", "show_command": True, "when": "tool_policy.shell.run_tests.permission == ask"},
                "before_sensitive_action": {"mode": _decision(session, "approval_style", "risk_card_with_reason")},
                "rule_update": {"mode": "diff_review", "requires_approval": True},
            },
            "memory": {
                "short_term": ["current_diff", "current_review_context", "current_user_feedback"],
                "long_term_candidates": _decision(session, "memory_scope", ["accepted_patterns", "false_positive_patterns", "project_rules"]),
                "update_policy": memory_policy,
                "update_requires_approval": memory_policy != "auto_low_risk_memory",
                "forbidden": ["credentials", "secrets", "unrelated_private_content"],
            },
            "output": {"format": output_format, "artifacts": artifacts},
            "eval": {
                "metrics": [
                    "finding_acceptance_rate",
                    "false_positive_rate",
                    "actionable_suggestion_rate",
                    "user_revision_count",
                ]
            },
        }
    )
    return spec


def _compile_writing_agent(session: PreSpecSession, agent_name: str | None) -> Dict[str, Any]:
    spec = _base(session, agent_name, "wechat-ai-writer")
    focus = _decision(session, "writing_focus", ["engineering_thinking", "ai_usage", "personal_practice"])
    material_sources = _decision(session, "material_sources", ["manual_input", "markdown_notes"])
    publish_policy = _decision(session, "publish_policy", "explicit_confirmation")
    output_package = _decision(session, "output_package", ["article_md", "title_options", "summary", "cover_prompt", "publish_checklist"])
    autonomy_level = _decision(session, "autonomy_level", "L2")
    initiative = _decision(session, "initiative_level", "weekly_suggestion")

    artifact_mapping = {
        "article_md": "article.md",
        "title_options": "title_options.md",
        "summary": "summary.md",
        "cover_prompt": "cover_prompt.md",
        "publish_checklist": "publish_checklist.md",
        "html_preview": "article_preview.html",
    }
    artifacts = [artifact_mapping[x] for x in output_package if x in artifact_mapping]

    publish_permission = "deny" if publish_policy == "never_publish" else "ask"
    spec.update(
        {
            "goal": {
                "primary": "帮助用户持续产出关于 AI 技巧、实践心得和工程化思考的公众号文章。",
                "secondary": ["降低选题成本", "沉淀写作风格", "减少重复修改", "生成完整发布包"],
                "focus": focus,
            },
            "lifecycle": {"mode": _decision(session, "lifecycle", "continuous"), "trigger": ["manual", initiative]},
            "autonomy": {
                "level": autonomy_level,
                "max_iterations_without_user": 3,
                "default_behavior": "draft_then_ask_at_key_checkpoints",
            },
            "inputs": {"required": ["material_or_topic"], "optional": ["notes", "style_rules", "previous_articles"]},
            "tools": {
                "required_capabilities": ["read_user_notes", "generate_markdown", "ask_user", "store_style_memory", "export_publish_package"]
            },
            "tool_policy": {
                "fs.read_notes": {"permission": "allow" if "markdown_notes" in material_sources else "ask", "scope": session.get_inputs("material_sources").get("notes_path", "configured_notes_path"), "risk": "medium"},
                "fs.write_draft": {"permission": "allow", "risk": "low"},
                "wechat.create_draft": {"permission": "ask", "risk": "high"},
                "wechat.publish": {"permission": publish_permission, "risk": "critical"},
            },
            "human_feedback": {
                "topic_selection": {"mode": _decision(session, "topic_feedback", "choice"), "options_count": "3-5"},
                "outline_review": {"mode": "structured_comment"},
                "draft_review": {"mode": _decision(session, "draft_feedback", "report_plus_chat")},
                "before_publish": {"mode": "explicit_approval", "required_phrase": "确认发布"},
                "style_rule_update": {"mode": "diff_review", "requires_approval": True},
            },
            "memory": {
                "short_term": ["current_article_goal", "current_feedback"],
                "long_term_candidates": _decision(session, "style_memory_scope", ["tone", "title_preference", "article_structure"]),
                "update_policy": _decision(session, "style_memory_policy", "approved_style_patch"),
                "update_requires_approval": True,
                "forbidden": ["credentials", "private_unrelated_content"],
            },
            "output": {"format": "publish_package", "artifacts": artifacts},
            "eval": {"metrics": ["user_edit_distance", "approval_rate", "revision_rounds", "style_match_score"]},
        }
    )
    return spec


def _compile_generic_agent(session: PreSpecSession, agent_name: str | None) -> Dict[str, Any]:
    spec = _base(session, agent_name, "custom-agent")
    spec.update(
        {
            "goal": {"primary": session.user_goal, "secondary": []},
            "lifecycle": {"mode": "on_demand", "trigger": ["manual"]},
            "autonomy": {"level": _decision(session, "autonomy_level", "L2"), "default_behavior": "auto_low_risk_ask_high_risk"},
            "inputs": {"required": ["user_request"], "optional": []},
            "tools": {"required_capabilities": ["ask_user", "generate_markdown"]},
            "tool_policy": {"default": {"permission": "ask", "risk": "medium"}},
            "human_feedback": {"default": {"mode": "approval"}},
            "memory": {"update_requires_approval": True},
            "output": {"artifacts": ["report.md"]},
            "eval": {"metrics": ["user_acceptance"]},
        }
    )
    return spec
